version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./src/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENV: dev
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: db
      DB_PORT: 5432
    command: >
      /bin/sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --reload
      "
    restart: always

volumes:
  postgres_data:
