# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY ./app /code/app
COPY migrations /code/migrations
COPY alembic.ini /code/
COPY requirements.txt /code/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV ENV=dev
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres123
ENV DB_HOST=localhost
ENV DB_PORT=5432

# Run app.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--workers", "4"]
